    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")
    // disable OS Authentication so I can share username in terminal and web context
    set props("AutheEnabled") = 2031
    do ##class(Security.System).Modify(, .props)

    zn "USER"
    zpm "load /home/irisowner/irisdev/ -dev -v":1:1
    do ##class(%Studio.SourceControl.Interface).SourceControlClassSet("SourceControl.Git.Extension")

    halt
